global:
  project_name: curdbee 
  
development: &non_production_settings
  site_url: http://localhost:3000
  site_name: CurdBee
  admin_email: lakshan@curdbee.com  
  
test:
  <<: *non_production_settings

staging:
  site_url: http://orete.org
  site_name: CurdBee
  admin_email: lakshan@curdbee.com  
  
production:
  site_url: http://www.curdbee.com
  site_name: CurdBee
  admin_email: lakshan@curdbee.com
